// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY29R07GlubY5lFmUriQ8qiVuiiWv7W6Y',
    appId: '1:981965097928:web:b08d7d1bfce182d3d4cefd',
    messagingSenderId: '981965097928',
    projectId: 'qio-app',
    authDomain: 'qio-app.firebaseapp.com',
    databaseURL: 'https://qio-app-default-rtdb.firebaseio.com',
    storageBucket: 'qio-app.firebasestorage.app',
    measurementId: 'G-EWCMYG70SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsqCztwlogBIyVpH1MR_kTsGNBgcwjb08',
    appId: '1:981965097928:android:1afa4bedefcdf0f6d4cefd',
    messagingSenderId: '981965097928',
    projectId: 'qio-app',
    databaseURL: 'https://qio-app-default-rtdb.firebaseio.com',
    storageBucket: 'qio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5AIEmM4Hhi3ZJhG9tP_XJuyeB7XGV5zg',
    appId: '1:981965097928:ios:b29b581959b843f7d4cefd',
    messagingSenderId: '981965097928',
    projectId: 'qio-app',
    databaseURL: 'https://qio-app-default-rtdb.firebaseio.com',
    storageBucket: 'qio-app.firebasestorage.app',
    iosBundleId: 'com.qio.qioApp',
  );
}
